// packages/solid/src/toast/title/ToastTitle.tsx
import { createEffect, onCleanup } from 'solid-js';
import { splitComponentProps } from '../../solid-helpers';
import type { BaseUIComponentProps } from '../../utils/types';
import { useId } from '../../utils/useId';
import { useRenderElement } from '../../utils/useRenderElement';
import { useToastRootContext } from '../root/ToastRootContext';

/**
 * A title that labels the toast.
 * Renders an `<h2>` element.
 *
 * Documentation: [Base UI Toast](https://base-ui.com/react/components/toast)
 */
export function ToastTitle(componentProps: ToastTitle.Props) {
  const [, local, elementProps] = splitComponentProps(componentProps, ['id', 'children']);
  const idProp = () => local.id;

  const { toast, setTitleId } = useToastRootContext();

  const id = useId(idProp);

  const shouldRender = () => 'children' in local;

  createEffect(() => {
    if (!shouldRender()) {
      return;
    }

    setTitleId(id());

    onCleanup(() => {
      setTitleId(undefined);
    });
  });

  const state: ToastTitle.State = {
    get type() {
      return toast().type;
    },
  };

  const element = useRenderElement('h2', componentProps, {
    enabled: shouldRender,
    state,
    props: [
      {
        get id() {
          return id();
        },
      },
      elementProps,
    ],
    get children() {
      return <>{local.children ?? toast().title}</>;
    },
  });

  return <>{element()}</>;
}

export interface ToastTitleState {
  /**
   * The type of the toast.
   */
  type: string | undefined;
}

export interface ToastTitleProps extends BaseUIComponentProps<'h2', ToastTitle.State> {}

export namespace ToastTitle {
  export type State = ToastTitleState;
  export type Props = ToastTitleProps;
}

// packages/react/src/toast/title/ToastTitle.tsx
'use client';
import { useId } from '@base-ui/utils/useId';
import { useIsoLayoutEffect } from '@base-ui/utils/useIsoLayoutEffect';
import * as React from 'react';
import type { BaseUIComponentProps } from '../../utils/types';
import { useRenderElement } from '../../utils/useRenderElement';
import { useToastRootContext } from '../root/ToastRootContext';

/**
 * A title that labels the toast.
 * Renders an `<h2>` element.
 *
 * Documentation: [Base UI Toast](https://base-ui.com/react/components/toast)
 */
export const ToastTitle = React.forwardRef(function ToastTitle(
  componentProps: ToastTitle.Props,
  forwardedRef: React.ForwardedRef<HTMLHeadingElement>,
) {
  const { render, className, id: idProp, children: childrenProp, ...elementProps } = componentProps;

  const { toast, setTitleId } = useToastRootContext();

  const children = childrenProp ?? toast.title;

  const shouldRender = Boolean(children);

  const id = useId(idProp);

  useIsoLayoutEffect(() => {
    if (!shouldRender) {
      return undefined;
    }

    setTitleId(id);

    return () => {
      setTitleId(undefined);
    };
  }, [shouldRender, id, setTitleId]);

  const state: ToastTitle.State = {
    type: toast.type,
  };

  const element = useRenderElement('h2', componentProps, {
    ref: forwardedRef,
    state,
    props: {
      ...elementProps,
      id,
      children,
    },
  });

  if (!shouldRender) {
    return null;
  }

  return element;
});

export interface ToastTitleState {
  /**
   * The type of the toast.
   */
  type: string | undefined;
}

export interface ToastTitleProps extends BaseUIComponentProps<'h2', ToastTitle.State> {}

export namespace ToastTitle {
  export type State = ToastTitleState;
  export type Props = ToastTitleProps;
}
