// docs-solid/src/components/CodeBlock.tsx
import { useId } from '@msviderok/base-ui-solid/utils';
import { useLocation } from '@solidjs/router';
import copy from 'clipboard-copy';
import clsx from 'clsx';
import { useGoogleAnalytics } from 'docs-solid/src/blocks/GoogleAnalyticsProvider';
import {
    createContext,
    createSignal,
    splitProps,
    useContext,
    type Accessor,
    type ComponentProps,
} from 'solid-js';
import { CheckIcon } from '../icons/CheckIcon';
import { CopyIcon } from '../icons/CopyIcon';
import { GhostButton } from './GhostButton';
import * as ScrollArea from './ScrollArea';

const CodeBlockContext = createContext<{
  codeId: Accessor<string>;
  titleId: Accessor<string>;
}>({ codeId: () => '', titleId: () => '' });

export function Root(componentProps: ComponentProps<'div'>) {
  const [local, props] = splitProps(componentProps, ['class']);
  const titleId = useId();
  const codeId = useId();
  const context = { codeId, titleId };
  return (
    <CodeBlockContext.Provider value={context}>
      <div
        role="figure"
        aria-labelledby={titleId()}
        class={clsx('CodeBlockRoot', local.class)}
        {...props}
      />
    </CodeBlockContext.Provider>
  );
}

export function Panel(componentProps: ComponentProps<'div'>) {
  const [local, props] = splitProps(componentProps, ['class', 'children']);
  const { codeId, titleId } = useContext(CodeBlockContext);
  const [copyTimeout, setCopyTimeout] = createSignal(0);

  return (
    <div class={clsx('CodeBlockPanel', local.class)} {...props}>
      <div id={titleId()} class="CodeBlockPanelTitle">
        {local.children}
      </div>
      <GhostButton
        class="ml-auto"
        aria-label="Copy code"
        onClick={async () => {
          const code = document.getElementById(codeId())?.textContent;

          if (code) {
            await copy(code);
            /* eslint-disable no-restricted-syntax */
            const newTimeout = window.setTimeout(() => {
              window.clearTimeout(newTimeout);
              setCopyTimeout(0);
            }, 2000);
            window.clearTimeout(copyTimeout());
            setCopyTimeout(newTimeout);
            /* eslint-enable no-restricted-syntax */
          }
        }}
      >
        Copy
        <span class="flex size-[14px] items-center justify-center">
          {copyTimeout() ? <CheckIcon /> : <CopyIcon />}
        </span>
      </GhostButton>
    </div>
  );
}

export function Pre(componentProps: ComponentProps<'pre'>) {
  const [local, props] = splitProps(componentProps, ['class']);
  const { codeId } = useContext(CodeBlockContext);
  return (
    <ScrollArea.Root
      // Select code block contents on Ctrl/Cmd + A
      tabIndex={-1}
      class="CodeBlockPreContainer"
      onKeyDown={(event) => {
        if (
          event.key === 'a' &&
          (event.metaKey || event.ctrlKey) &&
          !event.shiftKey &&
          !event.altKey
        ) {
          event.preventDefault();
          window.getSelection()?.selectAllChildren(event.currentTarget);
        }
      }}
    >
      <ScrollArea.Viewport
        style={{ overflow: undefined }}
        render={(p) => (
          <pre
            {...p}
            {...props}
            id={codeId()}
            class={clsx('CodeBlockPre', typeof p.class === 'string' ? p.class : '', local.class)}
            ref={(el) => {
              if (typeof p.ref === 'function') {
                p.ref(el);
              } else {
                p.ref = el;
              }
              if (typeof props.ref === 'function') {
                props.ref(el);
              } else {
                props.ref = el;
              }
            }}
          />
        )}
      />
      <ScrollArea.Scrollbar orientation="horizontal" />
    </ScrollArea.Root>
  );
}

// docs/src/components/CodeBlock.tsx
'use client';
import * as React from 'react';
import copy from 'clipboard-copy';
import clsx from 'clsx';
import { usePathname } from 'next/navigation';
import { useGoogleAnalytics } from 'docs/src/blocks/GoogleAnalyticsProvider';
import * as ScrollArea from './ScrollArea';
import { CopyIcon } from '../icons/CopyIcon';
import { CheckIcon } from '../icons/CheckIcon';
import { GhostButton } from './GhostButton';

const CodeBlockContext = React.createContext({ codeId: '', titleId: '' });

export function Root({ className, ...props }: React.ComponentPropsWithoutRef<'div'>) {
  const titleId = React.useId();
  const codeId = React.useId();
  const context = React.useMemo(() => ({ codeId, titleId }), [codeId, titleId]);
  return (
    <CodeBlockContext.Provider value={context}>
      <div
        role="figure"
        aria-labelledby={titleId}
        className={clsx('CodeBlockRoot', className)}
        {...props}
      />
    </CodeBlockContext.Provider>
  );
}

export function Panel({ className, children, ...props }: React.ComponentPropsWithoutRef<'div'>) {
  const { codeId, titleId } = React.useContext(CodeBlockContext);
  const [copyTimeout, setCopyTimeout] = React.useState<number>(0);
  const ga = useGoogleAnalytics();
  const pathname = usePathname();

  return (
    <div className={clsx('CodeBlockPanel', className)} {...props}>
      <div id={titleId} className="CodeBlockPanelTitle">
        {children}
      </div>
      <GhostButton
        className="ml-auto"
        aria-label="Copy code"
        onClick={async () => {
          const code = document.getElementById(codeId)?.textContent;

          if (code) {
            await copy(code);
            const title = document.getElementById(titleId)?.textContent ?? undefined;
            const codeBlockId = title ? `${pathname}#${title}` : pathname;
            ga?.trackEvent({
              category: 'code_block',
              action: 'copy',
              label: codeBlockId,
              params: { copy: codeBlockId, slug: title || '' },
            });
            /* eslint-disable no-restricted-syntax */
            const newTimeout = window.setTimeout(() => {
              window.clearTimeout(newTimeout);
              setCopyTimeout(0);
            }, 2000);
            window.clearTimeout(copyTimeout);
            setCopyTimeout(newTimeout);
            /* eslint-enable no-restricted-syntax */
          }
        }}
      >
        Copy
        <span className="flex size-[14px] items-center justify-center">
          {copyTimeout ? <CheckIcon /> : <CopyIcon />}
        </span>
      </GhostButton>
    </div>
  );
}

export function Pre({ className, ...props }: React.ComponentProps<'pre'>) {
  const { codeId } = React.useContext(CodeBlockContext);
  return (
    <ScrollArea.Root
      // Select code block contents on Ctrl/Cmd + A
      tabIndex={-1}
      className="CodeBlockPreContainer"
      onKeyDown={(event) => {
        if (
          event.key === 'a' &&
          (event.metaKey || event.ctrlKey) &&
          !event.shiftKey &&
          !event.altKey
        ) {
          event.preventDefault();
          window.getSelection()?.selectAllChildren(event.currentTarget);
        }
      }}
    >
      <ScrollArea.Viewport
        style={{ overflow: undefined }}
        render={<pre {...props} id={codeId} className={clsx('CodeBlockPre', className)} />}
      />
      <ScrollArea.Scrollbar orientation="horizontal" />
    </ScrollArea.Root>
  );
}
